# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Programmieren - Grundlegende Konzepte
author: Dr. Simon Praetorius (Institut für Wissenschaftliches Rechnen)
copyright: "2025"
logo:  images/logo3a.png

exclude_patterns: [_build, venv, .vscode, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: math-ba-pr10.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/spraetor/prog1  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

execute:
  execute_notebooks: cache

sphinx:
  config:
    language: de
    html_theme_options:
      logo:
        text: "Math-Ba-PR10 WS25/26"
        image_dark: images/logo3a.png
        image_light: images/logo3a_light.png

  extra_extensions:
    - sphinx_proof
    - sphinx_exercise
    - myst_nb
